; Projeto de exemplo do firmware EdgeData (ESP32-S3).
; Compile com:  pio run    |  grave com:  pio run -t upload  |  monitor:  pio device monitor

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    symlink://../edgedata-arduino
    bblanchon/ArduinoJson@^7.0.0
    h2zero/NimBLE-Arduino@^2.1.0
